services:
  frontend:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - cafeteria_network
    depends_on:
      - mysql      
  mysql:
    image: mysql:8.0
    env_file: .env.mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - cafeteria_network
    ports:
      - "3306:3306"

networks:
  cafeteria_network:
    driver: bridge